# Generated by Django 3.2.6 on 2021-09-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester_app', '0002_option_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
